modLoader="javafml"
loaderVersion="${loader_version_range}"
license="${mod_license}"

[[mods]]
modId="${mod_id}"
version="${mod_version}"
displayName="${mod_name}"
authors="${mod_authors}"
description='''${mod_description}'''

[[dependencies.${mod_id}]]
modId="neoforge"
type="required"
versionRange="${neo_version_range}"
ordering="NONE"
side="BOTH"

[[dependencies.${mod_id}]]
modId="minecraft"
type="required"
versionRange="${minecraft_version_range}"
ordering="NONE"
side="BOTH"

[[dependencies.${mod_id}]]
modId="guardvillagers"
type="required"
versionRange="[2.4.10,)"
ordering="AFTER"
side="BOTH"

[[dependencies.${mod_id}]]
modId="irons_spellbooks"
type="required"
versionRange="[1.21.1-3,)"
ordering="AFTER"
side="BOTH"

[[dependencies.${mod_id}]]
modId="spell_engine"
type="required"
versionRange="[1.9.9,)"
ordering="AFTER"
side="BOTH"

[[dependencies.${mod_id}]]
modId="spell_power"
type="required"
versionRange="[1.4.4,)"
ordering="AFTER"
side="BOTH"

[[dependencies.${mod_id}]]
modId="wizards"
type="required"
versionRange="[2.7.1,)"
ordering="AFTER"
side="BOTH"

[[dependencies.${mod_id}]]
modId="better_weaponry"
type="required"
versionRange="[1.1.3,)"
ordering="AFTER"
side="BOTH"

[[dependencies.${mod_id}]]
modId="bettercombat"
type="required"
versionRange="[2.3.2,)"
ordering="AFTER"
side="BOTH"

[[dependencies.${mod_id}]]
modId="better_mob_combat_reimagined"
type="required"
versionRange="[1.0.40,)"
ordering="AFTER"
side="BOTH"

[[dependencies.${mod_id}]]
modId="elemental_wizards_rpg"
type="optional"
versionRange="[2,)"
ordering="AFTER"
side="BOTH"

[[dependencies.${mod_id}]]
modId="lne_wizards"
type="optional"
versionRange="[1,)"
ordering="AFTER"
side="BOTH"

[[dependencies.${mod_id}]]
modId="archers"
type="optional"
versionRange="[2.7,)"
ordering="AFTER"
side="BOTH"

[[dependencies.${mod_id}]]
modId="archers_expansion"
type="optional"
versionRange="[1,)"
ordering="AFTER"
side="BOTH"

[[dependencies.${mod_id}]]
modId="paladins"
type="optional"
versionRange="[2.7,)"
ordering="AFTER"
side="BOTH"

[[dependencies.${mod_id}]]
modId="lne_paladins"
type="optional"
versionRange="[1,)"
ordering="AFTER"
side="BOTH"
